apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: k8-service
  labels:
    app: k8-service 
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: k8-service
  template:
    metadata:
      labels:
        tier: k8-service
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 81
