apiVersion: v1
kind: Service
metadata:
  name: k8-service
spec:
  type: NodePort
  ports:
  - name: nginx
    nodePort: 30081 # Listening port on External IPs
    port: 81 # Listening port on Internal IPs
    protocol: TCP
    targetPort: 80 # Pod’s listening port
  selector:
    tier: k8-service
