apiVersion: v1
kind: Service
metadata:
  name: nginx-dns
  labels:
    name: nginx-dns
spec:
  type: ExternalName
  externalName: example.com
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx-dns
