apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-dns
  labels:
    app: nginx-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-dns
  template:
    metadata:
      labels:
        app: nginx-dns
    spec:
      containers:
      - name: nginx
        image: nginx
